---
driver_plugin: docker
driver_config:
  privileged: true
  use_sudo: false
  eflags: container=docker
  require_chef_omnibus: 11.12.8

platforms:
  - name: debian-stretch

suites:
  - name: default
    run_list:
      - recipe[mopidy-jukebox]
    attributes: {}
